### ISSUE TITLE
k0di tools em OpenELEC 5.0.1

### ISSUE THREAD

**Issue by miguelcobain** [i96751414/anonymous-repo#5]
Não parece estar a funcionar em OpenELEC 5.0.1 + Raspberry Pi

Encontrei este post no fórum do kodi: http://openelec.tv/forum/124-raspberry-pi/75077-openelec-5-0-1-problem-librtmp-updated

Parece que mais utilizadores tiveram este problema.

**Comment by i96751414** [comment]
Não sou eu quem compila as libs e, como tal, não poderei fazer nada quanto
a isso. O addon apenas pegas nas libs já compiladas e actualiza... Mas
penso que para breve vão sair libs compativeis

2015-02-06 16:05 GMT+00:00 Miguel Andrade <notifications@github.com>:

**Comment by miguelcobain** [comment]
Testei agora em OpenELEC 5.0.0, também não funciona.

Alguma dica de onde posso compilar as libs eu mesmo?
