### ISSUE TITLE
Updated librtmp file

### ISSUE THREAD

**Issue by Shani-08** [i96751414/anonymous-repo#6]
Hi,
Is it possible for you to take my changes and update the librtmp file with your addon manager? If you can compile for all those plateforms then it would be great. My code exists at https://github.com/Shani-08/rtmpdump, it is the basic 2.4 rtmp+ksv patches+mine which solves the mips and other clone sending back id in return to their special command. This will be great help if you could update librtmp and then guys can use your addon to update their systems.
Let me know.

**Comment by i96751414** [comment]
Sure!
I have some compiled libs (from Superceleron) which contains your changes.

2015-02-07 19:18 GMT+00:00 Shani-08 <notifications@github.com>:

**Comment by Shani-08** [comment]
This is brilliant. So you have updated all platforms or just the one SuperCeleron?
If you could get other platforms compiled then it would superb and I'll peeps to your addon to update. Let me knew and I'll keep you in the loop if more changes are made.

**Comment by i96751414** [comment]
Sorry for the late reply,
Yes i've updated all platforms. As far as i know, only new openelec versions are not working with new libs and Armv7 is not supported. Cheers

**Comment by superceleron** [comment]
i96781414 in the mediafire folder there are libs to openelec 5.0.0 to 5.0.5 for pi 1 and pi 2 and they are working ok ;)
Btw i added android x86 if you noticed :)

**Comment by i96751414** [comment]
I will add those libs as soon as i can :) Thanks

2015-03-06 13:13 GMT+00:00 superceleron <notifications@github.com>:
