### ISSUE TITLE
[Android][K0di Tools] "Librtmp is corrupted"

### ISSUE THREAD

**Issue by RASMiranda** [i96751414/anonymous-repo#7]
K0di Tools for Librtmp was working fine, but since a couple of weeks ago it stoped working I get:
"Librtmp is corruped.\Please update again."
I tried playing with the (/mnt/asec/org.xbmc.kodi-1/lib/librtmp.so)/data/data/org.xbmc.xbmc/lib/librtmp.so file, first tried to delete the file (backuping) but got an error saying that it could not found the file.
Then I tried the file from kodi.wiki: http://www.mediafire.com/download/b5mbfswf4x3z7kq/librtmp.so
But still got "Librtmp is corruped.\Please update again."
I'll attach the original librtmp.so that was being used: https://www.mediafire.com/?9r5242uuo6b2gie

Any idea of what it might be?
Or where could I start looking? I have some experience in Python, but zero in Kodi stuff.

**Comment by i96751414** [comment]
É estranho isso acontecer. Pelo path que indicaste, estás em Android, certo?
Em caso afirmativo, tenta meter esta lib:
http://anonymous-repo.googlecode.com/svn/trunk/xbmc-tools/librtmp/Android/librtmp.so
(em /data/data/org.xbmc.xbmc/lib/)
O Android fez recentemente actualizações?


2015-02-27 21:58 GMT+00:00 Rui Miranda <notifications@github.com>:

**Comment by RASMiranda** [comment]
Obrigado pela resposta.
Colocando o librtmp.so que indicaste, o K0di Tools diz "Your librtmp is up to date", recomendas a tentar o update de qualquer maneira? Só para testar?

**Comment by RASMiranda** [comment]
Obrigado pela resposta.
Colocando o librtmp.so que indicaste, o K0di Tools diz "Your librtmp is up to date", quando faço o update mesmo assim, já o faz com sucesso!
Obrigado.

**Comment by i96751414** [comment]
Impecável. No entanto é estranho ter deixado de funcionar.. Parece que algo
mudou na lib.

No dia 28 de fevereiro de 2015 às 19:16, Rui Miranda <
notifications@github.com> escreveu:
