### ISSUE TITLE
librtmp -> openelec -> RaspberryPi

### ISSUE THREAD

**Issue by nmvle** [i96751414/anonymous-repo#8]
Hi,

Using OpenElec on RaspberryPi you don't have a sudo password. sudo comand does't even exists...

Thanks,

**Comment by i96751414** [comment]
Hi, thats happening because sometimes xbmc/kodi doesn't detect you O.S.
In this case, you need to force openElec OS at the addon settings.
BTW, soon ill release a new version of this addon

2015-03-30 17:36 GMT+01:00 nmvle <notifications@github.com>:
